# https://goreleaser.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: git-tree

before:
  hooks:
    - go mod tidy

builds:
  - id: git-tree
    main: .
    binary: git-tree
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386
  - id: git-tree-darwin
    main: .
    binary: git-tree
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids:
      - git-tree
      - git-tree-darwin
    format_overrides:
      - goos: windows
        formats: [zip]
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: homebrew
    ids:
      - git-tree-darwin
    formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: anton-dovnar
    name: git-tree
  footer: |-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - name: git-tree
    tap:
      owner: anton-dovnar
      name: homebrew-git-tree
    folder: Formula
    homepage: "https://github.com/anton-dovnar/git-tree"
    description: "Visualize a git repository’s commit history as an interactive graph."
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "git-tree"
