# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitTree < Formula
  desc "Visualize a git repository’s commit history as an interactive graph."
  homepage "https://github.com/anton-dovnar/git-tree"
  version "0.1.9"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/anton-dovnar/git-tree/releases/download/v0.1.9/git-tree_Darwin_x86_64.zip"
    sha256 "4b53461ac6bae85c2c4a5fcf6d81a284ee2a17c0496627361468f867e7c8b957"

    def install
      bin.install "git-tree"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/anton-dovnar/git-tree/releases/download/v0.1.9/git-tree_Darwin_arm64.zip"
    sha256 "291185cc4a8f587af09ad106c65a49c6ca37f7c311f6dfdfdb80a74f61637b75"

    def install
      bin.install "git-tree"
    end
  end
end
